export const FETCH_CHANNEL = 'FETCH_CHANNEL';
export const FETCH_CHANNEL_DETAIL = 'FETCH_CHANNEL_DETAIL';
export const FETCH_SCHEDULE = 'FETCH_SCHEDULE';
export const FAVORITE_CHANNEL_ADD = 'FAVORITE_CHANNEL_ADD';
export const FAVORITE_CHANNEL_DELETE = 'FAVORITE_CHANNEL_DELETE';
